### ISSUE TITLE
Wowmapper crashes WoW launches

### ISSUE THREAD

**Issue by Libertherme** [topher-au/WoWmapper#39]
Hi,

I set up wowmapper on my laptop at work last night and got it working fine, however when trying this morning at home whenever I start the game client wowmapper crashes.
It will sit fine on the desktop, and with the battle.net client open, however after pressing "Start" to start the game, as soon as the icon appears on the taskbar for the game client wowmapper crashes.

All that the windows logs show is "Process was terminated due to an unhanded exception. Exception code c0000005"

**Comment by gbeech** [comment]
Also having same issue with wowmapper crash on game launch, if I minimise wow after the crash and re-launch wowmapper it works as normal.
Issue has occured in last few versions. I don't have memory reading enabled. Default options apart from modifier set to Triggers.
Using Windows 10 X64.

I get the following 2 errors in the event log

Application: WoWmapper.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.ComponentModel.Win32Exception
   at System.Diagnostics.NtProcessManager.GetModuleInfos(Int32, Boolean)
   at System.Diagnostics.NtProcessManager.GetFirstModuleInfo(Int32)
   at System.Diagnostics.Process.get_MainModule()
   at WoWmapper.ConsolePort.BindWriter.WriteBinds()
   at WoWmapper.WorldOfWarcraft.ProcessManager.ProcessThreadMethod()
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Threading.ThreadHelper.ThreadStart()

Faulting application name: WoWmapper.exe, version: 7.1.2.0, time stamp: 0x57ca5acc
Faulting module name: KERNELBASE.dll, version: 10.0.14393.0, time stamp: 0x57899809
Exception code: 0xe0434352
Fault offset: 0x0000000000017788
Faulting process ID: 0x52d4
Faulting application start time: 0x01d206c65f6640b6
Faulting application path: C:\Users\USERNAME\AppData\Local\WoWmapper\WoWmapper.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report ID: e8d29dda-c475-48c3-80e7-0877fa431b5e
Faulting package full name: 
Faulting package-relative application ID:

**Comment by topher-au** [comment]
Hey guys, I'll be putting out a new version soon which will hopefully solve the issue. If it happens again, grab log.txt from the WoWmapper folder and post the details there, hopefully will give some more insight.

Thanks

**Comment by gbeech** [comment]
Many Thanks, that's fixed it.

**Comment by Libertherme** [comment]
Apologies for the late reply, I thought I'd responded already. 
That fixed the issue for me too - thank you very much!
