### ISSUE TITLE
WoWmapper crashes

### ISSUE THREAD

**Issue by saxwen** [topher-au/WoWmapper#44]
Every time I click on wowmapper to load is shows up in the hidden icons tab then disappears without loading. Not sure what I need to do to get it to run. I tried running as administrator and still wont load.

**Comment by xCHEVYx** [comment]
I'm having this same issue. and when I pull the log text this is what I'm getting

[8:41:42 PM] Controller manager starting up...
[8:41:42 PM] Searching for DS4 controllers...
[8:41:42 PM] XInput interface starting up
[8:41:42 PM] Loading XInput 10 wrapper...
[8:41:42 PM] XInput 10 wrapper loaded.
[8:41:42 PM] Registered for USB events with handle [2417752861392]

but it doesn't work. and please advise if this actually works with windows 10 because in the properties under compatibility it only goes to windows 8

**Comment by marcusfollrud** [comment]
I get the same error. Here's the windows log:
Application: WoWmapper.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.DllNotFoundException
   at WoWmapper.Controllers.Xbox.XInput10.XInputGetState(Int32, J2i.Net.XInputWrapper.XInputState ByRef)
   at J2i.Net.XInputWrapper.XboxController.UpdateState()
   at J2i.Net.XInputWrapper.XboxController.PollerLoop()
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Threading.ThreadHelper.ThreadStart()

**Comment by topher-au** [comment]
Try with the latest version guys, should be working now.
