### ISSUE TITLE
Exception Occurred on Startup

### ISSUE THREAD

**Issue by xMiachix** [topher-au/WoWmapper#75]
When starting wowmapper it says an Exception occurred, and this is what it says:
Exception occurred: System.Threading.AbandonedMutexException: The wait completed due to an abandoned mutex.
   at System.Threading.WaitHandle.ThrowAbandonedMutexException()
   at System.Threading.WaitHandle.InternalWaitOne(SafeHandle waitableSafeHandle, Int64 millisecondsTimeout, Boolean hasThreadAffinity, Boolean exitContext)
   at System.Threading.WaitHandle.WaitOne(Int32 millisecondsTimeout, Boolean exitContext)
   at WoWmapper.App.OnStartup(StartupEventArgs e)
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
Stack trace:
   at System.Threading.WaitHandle.ThrowAbandonedMutexException()
   at System.Threading.WaitHandle.InternalWaitOne(SafeHandle waitableSafeHandle, Int64 millisecondsTimeout, Boolean hasThreadAffinity, Boolean exitContext)
   at System.Threading.WaitHandle.WaitOne(Int32 millisecondsTimeout, Boolean exitContext)
   at WoWmapper.App.OnStartup(StartupEventArgs e)
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

any help please?

**Comment by eTzmNcbkrng** [comment]
Reinstall and reboot fixed this error for a user in our Discord.
https://discord.gg/T4jv3X

**Comment by seblindfors** [comment]
You can also append `--ignore-mutex` in the target field in the properties of the application shortcut. This circumvents the mutex timeout issue.
